### ISSUE TITLE
`changed-markdown-files` should be `changed-files`

### ISSUE THREAD

**Issue by rafrafek** [developer-friendly/blog#38]
Hi!

I think `changed-markdown-files` should be changed to just `changed-files` here:

https://github.com/developer-friendly/blog/blob/932e49325177427f97a30a63dbea9c3175ac5748/docs/blog/codes/2024/0004-dynamic-github-actions-matrix/step2-determine.yml#L12

and here:
https://github.com/developer-friendly/blog/blob/932e49325177427f97a30a63dbea9c3175ac5748/docs/blog/codes/2024/0004-dynamic-github-actions-matrix/full-ci-definition.yml#L44

Links:

The article:
https://developer-friendly.blog/blog/2024/03/09/github-actions-dynamic-matrix/

The code repo:
https://github.com/meysam81/github-actions-dynamic-matrix

**Comment by rafrafek** [comment]
Please look at the discussion here, there are some other fixes https://github.com/tj-actions/changed-files/discussions/2245

**Comment by rafrafek** [comment]
Links:

The article:
https://developer-friendly.blog/blog/2024/03/09/github-actions-dynamic-matrix/

The code repo:
https://github.com/meysam81/github-actions-dynamic-matrix

**Comment by meysam81** [comment]
Hey @rafrafek 

Thanks for your initiative :hugs: 

I have dealt with the other issue (#37).

I will deal with this one when I get some time. In the meantime, any contribution is welcome if you've already sort it out on your end. :rose: 

Regards.

**Comment by rafrafek** [comment]
Hey @meysam81,

I did the fix for the `meysam81/github-actions-dynamic-matrix` repo, please review and update the article.

https://github.com/meysam81/github-actions-dynamic-matrix/pull/1
